#Based on https://github.com/itwonderlab/ansible-vbox-vagrant-kubernetes/

IMAGE_NAME = "debian/buster64"
K8S_NAME = "suuper-k8s"

MASTER_MEM = 3072
MASTER_CPU = 2

NODES = 2
NODES_CPU = 2
NODES_MEM = 3072

IP_BASE = "192.168.50."

Vagrant.configure("2") do |config|
  config.vm.define "k8s-m" do |master|
    master.vm.box = IMAGE_NAME
    master.vm.network :private_network, :ip => "#{IP_BASE}#{10}"
    master.vm.hostname = "k8s-m"
    master.vm.provider "libvirt" do |domain|
      domain.memory = MASTER_MEM
      domain.cpus = MASTER_CPU
    end
    master.vm.provision "ansible" do |ansible|
      ansible.playbook = "roles/k8s.yml"
      #redefine defaults
      ansible.extra_vars = {
        k8s_cluster_name: K8S_NAME,
        k8s_master_admin_user: "vagrant",
        k8s_master_admin_group: "vagrant",
        k8s_master_apiserver_advertise_address: "#{IP_BASE}#{10}",
        k8s_master_node_name: "k8s-m",
        k8s_node_public_ip: "#{IP_BASE}#{10}"
      }
    end
  end

  (1..NODES).each do |i|
    config.vm.define "k8s-n-#{i}" do |node|
      node.vm.box = IMAGE_NAME
      node.vm.network :private_network, :ip => "#{IP_BASE}#{20 + i}"
      node.vm.hostname = "k8s-n-#{i}"
      node.vm.provider "libvirt" do |domain|
        domain.memory = NODES_MEM
        domain.cpus = NODES_CPU
      end
      node.vm.provision "ansible" do |ansible|
        ansible.playbook = "roles/k8s.yml"
        #redefine defaults
        ansible.extra_vars = {
          k8s_cluster_name: K8S_NAME,
          k8s_node_admin_user: "vagrant",
          k8s_node_admin_group: "vagrant",
          k8s_node_public_ip: "#{IP_BASE}#{20 + i}"
        }
      end
    end
  end
end