- name: Create frontend deployment
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Deployment
      metadata:
        name: front-end
        labels:
          app: front-end
          version: v1
        namespace: sock-shop
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: front-end
            version: v1
        template:
          metadata:
            labels:
              app: front-end
              version: v1
          spec:
            terminationGracePeriodSeconds: 5
            containers:
            - name: front-end
              image: weaveworksdemos/front-end:0.3.12
              resources:
                limits:
                  cpu: 300m
                  memory: 1000Mi
                requests:
                  cpu: 100m
                  memory: 300Mi
              ports:
              - containerPort: 8079
              env:
              - name: SESSION_REDIS
                value: "true"
              securityContext:
                runAsNonRoot: true
                runAsUser: 10001
                capabilities:
                  drop:
                    - all
                readOnlyRootFilesystem: true
              livenessProbe:
                httpGet:
                  path: /
                  port: 8079
                initialDelaySeconds: 300
                periodSeconds: 3
              readinessProbe:
                httpGet:
                  path: /
                  port: 8079
                initialDelaySeconds: 30
                periodSeconds: 3
            nodeSelector:
              beta.kubernetes.io/os: linux

- name: Create frontend service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: front-end
        annotations:
          prometheus.io/scrape: 'true'
        labels:
          name: front-end
        namespace: sock-shop
      spec:
        type: ClusterIP
        ports:
          - name: http
            port: 80
            targetPort: 8079
        selector:
          app: front-end
